### ISSUE TITLE
Add std exceptions to readme

### ISSUE THREAD

**Issue by dagophil** [ToruNiina/toml11#107]
Hello and thank you for the great library.

The readme file says the following about [exceptions](https://github.com/ToruNiina/toml11#exceptions):

> All the exceptions thrown by toml11 inherits toml::exception that inherits std::exception.

However, this is not true. Many toml11 functions throw one of the `std` exceptions, for example, `std::out_of_range` or `std::runtime_error`.

Do you think it makes sense to update the readme accordingly?

**Comment by ToruNiina** [comment]
You are right. It should be fixed. I'm re-writing the README now and will soon be pushed.

----

Related:

Since now `toml::exception` has `toml::source_location`, I think the ideal way is to add `toml::out_of_range` and use it instead of `std::*`. (`std::runtime_error` might be thrown from where any `toml::source_location` cannot be created). But it breaks the backward compatibility, so, for now, I will leave it. Later I will improve that part with other problems that should be resolved (actually, `toml::result` was introduced to return an error type explicitly, like Rust or Go, but I did not yet implement that feature).

**Comment by dagophil** [comment]
Thank you for the quick response and for adding it to the readme :)
