### ISSUE TITLE
Preserving original order

### ISSUE THREAD

**Issue by KangJH** [ToruNiina/toml11#111]
Hi
Is there a way to preserve original order of toml file?
This question is similar with #71. 
So, I changed my code to use `toml::parse<toml::preserve_comments, std::map, std::deque>`.
But it still does not preserve original order.
I also tried `nlohmann::fifo_map`, but it does not seems to support table array and nested table quite well. 
Can you recommend a way to preserve original order of toml file?

**Comment by ToruNiina** [comment]
The serializer dumps the content in the same order as the container has. Since `std::map::iterator` iterates over the elements from the smallest to the largest, according to the given comparator (by default `std::less`), the resulting toml file will be sorted by its key. So using `std::map` does not preserve the order of definition.
I have no idea why nlohmann/fifo_map fails, but you can try another library, for example, https://github.com/Tessil/ordered-map.
For the arrays, `std::vector` already preserves the order, so you don't need to change it to `std::deque`.

**Comment by KangJH** [comment]
Thanks, tsl::ordered_map works perfectly!
 FYI, I've changed 2 parts.
1. `toml::parse<toml::preserve_comments, tsl::ordered_map, std::vector>(filename)`
2. `using value = basic_value<preserve_comments, tsl::ordered_map, std::vector>;` in value.hpp

When I changed parse part(no.1) only, the nested table was not ordered well.
But, when I applied  parsing part and toml::value definition both, it's working well.

Thank you very much
Have a nice day.

**Comment by ToruNiina** [comment]
Great! And thank you for the detailed information.

The default `toml::table` is defined as `toml::value::table_type`. Without modifying the defualt definition of `toml::value`, after converting a value into `toml::table`, the elements will be sorted, unexpectedly.

I know it is a confusing behavior. But, AFAIK, there is no way to automatically change the `toml::table` that is an alias without any template argument depending on the customized toml::value.

Note that, you can obtain the actual `table_type` used in the `toml::basic_value<...>` via `typename basic_value<...>::table_type`.

```cpp
auto file = toml::parse<toml::preserve_comment, tsl::ordered_map>(filename);
auto tables = toml::find<
        std::vector<typename decltype(file)::table_type>
    >(file, "array_of_table");
```

But yes, this code looks strange.

**Comment by neptuwunium** [comment]
This no longer works since sometime in 2025, with the change to type_config it is a bit different.

Though, tsl::ordered_map cannot compile with toml11 anymore if -fpermissive is not provided. It just fails around const correctness errors.

The solution as follows:

```cxx
using toml_table = toml::basic_value<toml::ordered_type_config>::table_type;

auto table = toml::parse<toml::ordered_type_config>meow.toml");

if(!table.contains("nya") || !table.at("nya").is_table())  table["nya"] = toml_table();

table["nya"]["value"] = 1;
```

xref #133 for mention reference since tsl::ordered_map is also used there.

putting this here because this is the first result on web search for toml preserving insertion order.
