### ISSUE TITLE
Is it safe to use pointer to data inside a table?

### ISSUE THREAD

**Issue by xidera5949** [ToruNiina/toml11#116]
Sorry if the question is stupid, I'm new to C++
I ask because using pointers in dynamic arrays is unsafe.
For example:
```
	int main()
	{
		std::vector<int> vec {1, 2, 3};
		auto p = &vec[1]; // It's ok for now

		vec.reserve(100500); // After that, the pointer p is invalid

		return 0;
	}
```
How about toml? Is it safe to use the data pointer like this:
```
	auto data = &toml::find(table, key);
	// And after that add more data to the table
```
Or like this:
`	auto data = &toml::find(array, index);`

**Comment by ToruNiina** [comment]
Yes, the condition under pointers are invalidated is complicated.

Basically, as long as you are dealing with tables, insertion does not change a pointer. But, note that, insertion can invalidate an iterator. On the other hand, erasing elements invalidates only pointers that point to the erased element.

Since, by default, `toml::value` uses `std::unordered_map` and `std::vector` inside, the condition when the pointer would be invalidated is the same as that of those. When you change the underlying container, the condition also changes.

I think [this stackoverflow answer](https://stackoverflow.com/a/54004916) explains well the conditions in detail.

**Comment by xidera5949** [comment]
Understood. Thank you very much!
