### ISSUE TITLE
How to get unused (extraneous) keys

### ISSUE THREAD

**Issue by boramalper** [ToruNiina/toml11#125]
Hi!

Thank you for your hard work, we really enjoy using it in my team and it made our lives much easier!

My question is whether there is a method (or a design pattern) to warn for "unused" (extraneous) keys. I am working on a rapidly evolving prototype and thus our input file changes quite often too, and it would be nice to be able to warn the user for unused keys as they are possibly a mistake.

Thanks again!

**Comment by ToruNiina** [comment]
Hi, thank you for using it.

Sorry, but currently, it does not have the feature.

Actually I also considered to implement that but in my case I could list up all the keys required in my application. But it seems that it's not in your case.

Since toml::value can be modified (unless it is marked as const), it is possible to erase key-value pair from a table after you read the pair. Then you can loop over the remained ("unused") key-value pairs and warn it. Because `toml::value` uses an `unordered_map` as a table, you can cast it via `as_table()` and call `erase(key)`. But I'm not sure this is a practical way because often keys are referenced more than once.

As a similar way, you can add prefix or suffix (e.g. `_`) to keys you referenced. It keeps values, but makes it painful to find a value that is already referenced because they would have a different name.

Implementing this feature means that key or value type has an additional `bool` value. Maybe value is more suitable because array does not have a key (it uses index) but has elements. Also, the definition of "used" is also a concern. Such as, an array that only the first element is used is "used"? or something like that. So I want to consider it carefully.

**Comment by boramalper** [comment]
I see, thanks!
