### ISSUE TITLE
Serialize json format

### ISSUE THREAD

**Issue by KangJH** [ToruNiina/toml11#132]
Does toml11 have serialization function to json format and vice versa?

**Comment by ToruNiina** [comment]
Although it is not included in the main directory, there is [a serialization function here](https://github.com/ToruNiina/toml11/blob/master/tests/check_toml_test.cpp). You can use it. Since it is not a header file, you would need to extract the serialization function from the file.

The reason why it is not included in the main directory is that this file is for language-agnostic spec test, and the format in JSON depends on one's purpose. For example, it has a type tag that might not be needed for other purposes (remember TOML spec requires to distinguish integer and floating point number). So you may need to modify the output part a bit for your own purpose.

On the other hand, toml11 does not have json parser nor json library interop. There are a large number of JSON libraries in the world and I cannot select one from them (supporting all of them is practically impossible). But, since toml11 supports value construction from STL containers, it should be possible to write a conversion function from JSON value to TOML value. If you have a specific JSON library candidate and/or a question about type conversion, ask me here.

**Comment by KangJH** [comment]
Thank you for the answer. will check the serialization function and use it.

**Comment by KangJH** [comment]
Just FYI. I've made a json converter function using your recommendation.
I just left a link for anyone interested.
(https://github.com/KangJH/toml11tojson)
