### ISSUE TITLE
where is “example.toml”?

### ISSUE THREAD

**Issue by baby7305** [ToruNiina/toml11#147]
I run the readme demo, can't find example.toml
```
# example.toml
title  = "hczn"
nums = [1,2,3]
name = "baby7305"
```
about below,
```
if(not data.at("a").contains("b"))
    {
        data["a"]["b"] = "c";
    }
```
how can I write the toml file?

**Comment by ToruNiina** [comment]
Sorry, but this repository does not include a concrete `example.toml`. The example just shows that some features (such as, ) and representative APIs this library has.

The code snippet you pasted here does the following.
- it assumes there is a table named `a` in the file.
- it checks if a table named `a` contains a value of which key is `b`.
- if it does not contains, it assigns a string `"c"` to a value named `b`.
- otherwise, it does not do anything.

So a file something like
```toml
title = "hczn"
nums = [1,2,3]
name = "baby7305"
[a]
foo = "bar"
```
does work, I think.

I will modity the example code to make it more easier to get.

**Comment by baby7305** [comment]
Thanks，✧*｡٩(^㉨^*)و✧*｡
