### ISSUE TITLE
Appending a constructed table

### ISSUE THREAD

**Issue by ravipathuri** [ToruNiina/toml11#154]
As in https://github.com/ToruNiina/toml11#constructing-a-tomlvalue , in case of constructing a table, the syntax looked like
toml::value v{{"foo", 42}, {"bar", 3.14}, {"baz", "qux"}};
To the above constructed table, how can we append one more key value pair. Is there such a provision in the current implementation?

**Comment by ToruNiina** [comment]
As explained in [the README](https://github.com/ToruNiina/toml11#operator), `toml::value::operator[](const std::string& key)` works in the same way as `std::unordered_map`. So, you can append a new key-value pair in the following way.

```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    toml::value v{{"foo", 42}, {"bar", 3.14}, {"baz", "qux"}};

    v["hoge"] = "piyo";

    std::cout << v << std::endl;
    // hoge = "piyo"
    // baz = "qux"
    // bar = 3.14
    // foo = 42

    return 0;
}
```

Also, you can manipulate an underlying container (by default, `std::unordered_map`) via `toml::value::as_table()` because it returns a modifiable reference to the container. The documentation about `as_xxx()` is [here](https://github.com/ToruNiina/toml11#as_xxx).

**Comment by ravipathuri** [comment]
Thanks for the clarification. Populating the key-value pairs is understood. But how can we populate the table header in a separate step?
