### ISSUE TITLE
[Feature request] Use find_or() like find() to pass many arguments as the number of subtables

### ISSUE THREAD

**Issue by BinWang0213** [ToruNiina/toml11#156]
Thanks for your nice library.

I enjoy to use `toml::find<bool>(data, "physics", "advection", "invert_flow");` to get a value from a file.

Why not implement `find_or()` similar to `find()` to return a default value if it not exists?
such as
 `toml::find_or<bool>(data, "physics", "advection", "invert_flow", false);`

**Comment by ToruNiina** [comment]
Hi,

Thank you for good suggestion. That is a nice idea.

I actually have tried to implement almost the same feature before and gave up because of its complexity. The template parameter pack takes all the arguments, so it requires additional effort to use the very last argument in a special purpose.

But I will try it again.

**Comment by BinWang0213** [comment]
Thanks a lot for your nice library.

If you finish this, you can update the ReadMe.md as well, I believe many people will like this feature.

**Comment by ToruNiina** [comment]
I have implemented it and merged. Now you can use it and the next release will include it. closing.
