### ISSUE TITLE
foo = [ { bar="\"{{baz}}\""} ] roundtrips broken

### ISSUE THREAD

**Issue by monkeydom** [ToruNiina/toml11#162]
default settings makes that a 
```
bar=""""{{baz}}""""
```
so probably just a missing check if the last character in a string is a quote when choosing triple quotes for output

**Comment by ToruNiina** [comment]
Actually, [the spec](https://toml.io/en/v1.0.0#string) allows to use one or two consecutive `"` anywhere in a multi-line string.

> You can write a quotation mark, or two adjacent quotation marks, anywhere inside a multi-line basic string. They can also be written just inside the delimiters.
> ```toml
> str4 = """Here are two quotation marks: "". Simple enough."""
> # str5 = """Here are three quotation marks: """."""  # INVALID
> str5 = """Here are three quotation marks: ""\"."""
> str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""
>
> # "This," she said, "is just a pointless statement."
> str7 = """"This," she said, "is just a pointless statement.""""
> ```

Here, only the `str5` is invalid because it uses 3 quotes (`"""`) inside. As you can see in the `str7`, using `"` just before closing delimiter is explicitly allowed.

This means that the following toml file is valid and should be parsed in the same way as `"\"{{baz}}\""`.

```toml
bar = """"{{baz}}""""
```

And the following code prints `"{{baz}}"`, as expected.

```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    using namespace toml::literals::toml_literals;
    const auto data = "\"\"\"\"{{baz}}\"\"\"\""_toml;
    std::cout << toml::get<std::string>(data) << std::endl;
    return 0;
}
```

So, it seems that both the parser and the serializer are correct.

----

Do you want to have an option to force serializer to print a string as a one-line basic string? It is sometimes demanded, but adding an option to all the `toml::string`s is a big change.

**Comment by monkeydom** [comment]
Oh, ic, thanks. I accidentally used another toml implementation to round trip, which seems to not have the case of `str7` right and reports an error there. 

Thanks for the quick response and clarification. I'm actually migrating from `cpptoml` because it doesn't support the 1.0.0 spec anymore, and an old binary using this was the cause of the report. So good to know that migration is worth it alone for proper string handling. At the current point I'm not sure yet what kind of customization for serialization will be helpful to my use case. But If I do have feature requests I'll file them again.

**Comment by ToruNiina** [comment]
This is just a comment, but the features I mentioned in the above is introduced in [v1.0.0-rc1](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#100-rc1--2020-04-01). In the v0.5.0, the interpretation of `""""foo""""` was not well-defined. So, in this sense, cpptoml is toml v0.5.0 standard compliant.

**Comment by monkeydom** [comment]
Thanks fore the clarification! Makes sense, and good that it is defined now. Good things to get sorted out before hitting a 1.0 ^^
