### ISSUE TITLE
Dot syntax for getting value within tables

### ISSUE THREAD

**Issue by Markus-included** [ToruNiina/toml11#174]
I would like to have convienient a syntax like this: `toml::find(file, "Game.Name")` to pull this value: 
```toml
[Game]
Name = "Name of a game"
```

**Comment by ToruNiina** [comment]
In TOML, a kay can include a dot (though it is not the best practice).

```toml
"Game.Name" = "Name of a game"
```

This is a valid TOML file and the structure is equivalent to the following JSON.

```json
{"Game.Name": "Name of a game"}
```

In toml11, `toml::find(file, "Game.Name")` corresponds to this case (`"Game.Name" = "Name of a game"`).

Of course I know a key including dots is not recommended, but this library is for general purpose and it sometimes makes sense to use dots in a key. For example, IP address or URL. So I want to strictly  distinguish those cases.

For your purpose, you can use `toml::find(file, "Game", "Name")` and, at least to me, it represents the recursive structure more clearly. The function can take as many number of keys you want. Does this function works with your case?

**Comment by mchaptel** [comment]
I think it could be very useful to make an overload for this function which gets the full dot string and splits it then under the hood then uses the multiple arguments find function to access the value. This would make the library able to access keys based on the inherent structure of the data inside the file as opposed to based on how it was written.

**Comment by mchaptel** [comment]
Hm, I didn't realize that. This is a very strange contradiction to me on the specs part. I guess it makes sense because of the optional inclusion of the quote marks but poses a problem for any compatibility with basically any other serialized format...

I have been using at_path extensively for that reason in fact. Thanks for letting me know, this is an interesting point to consider.

**Comment by ToruNiina** [comment]
Thanks @marzer, your explanation is (of course) perfect.

@mchaptel,
As marzer said, quoted keys are different from bare keys. bare keys only contain `0-9a-zA-Z_-`, but quoted keys may contain any unicode characters including dots, because the range of the key is explicit (quote should be escaped, though).

Generally a language spec is hard to read. If you find something that you think is weird, you can try other references. For toml, there is a language-agnostic test suite, [toml-test](https://github.com/BurntSushi/toml-test), which contains many valid toml files with the corresponding json files. In this case, you can see many examples in [tests/valid/key/quoted-dots.toml](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/key/quoted-dots.toml) and [.json](https://github.com/BurntSushi/toml-test/blob/master/tests/valid/key/quoted-dots.json). From the examples, you can see that the toml standard is well defined so there is no problem when converting a toml file to json (or any other config file format) and vice versa.
Both toml11 and toml++ (and many other well-known libraries) pass all the `toml-test`s. This means that these libraries conform to the standard and handle many edge cases correctly.

But I digress. The original comment is about a way to extract a value from a nested table. In the last comment, I pointed out that toml11 already has `toml::find(table, key1, key2, ...)` which does exactly this, and asked if this was sufficient or not.
I still think this function is sufficient because it works and there is no ambiguity.
The potential problem here is that `toml::find` only takes a fixed number of keys. In my experience, I have never found this to be a real problem, because the structure of the config file is mostly defined by the application itself that reads it. If there is a realistic and compelling situation where the nesting depth is unstable, I will consider implementing it.

Note that you can write dot-syntax based function by recursively `toml::find`-ing subtables after splitting a string by dots.

**Comment by marzer** [comment]
@mchaptel there's no way to do that sort of thing dynamically in C++ (i.e. like you might do it in python by unpacking a list), since C++ is all statically-typed. Function arguments need to be known in advance, and can't be dynamically determined at runtime (unless you want to start messing with C-style `va_args`, but _you really don't want to do that!_).

The way to do it would be per-subkey, querying for children as you go. If you want a generic example you can start from and mess with, toml++'s at_path() is built on top of this implementation function: [`toml::impl::parse_path()`](https://github.com/marzer/tomlplusplus/blob/ad55bae8a11a6eee39e2292b01e95b529b105767/include/toml%2B%2B/impl/at_path.inl#L29-L206). That gets called with some callbacks that take action when a subkey or index is encountered ([here]( https://github.com/marzer/tomlplusplus/blob/ad55bae8a11a6eee39e2292b01e95b529b105767/include/toml%2B%2B/impl/at_path.inl#L212-L254)). That should be fully-featured enough that you could copy+paste it into whatever toy project you have with whatever C++ toml library you wish to use (e.g. if you wanted to pair toml11's comment preservation with toml++'s at_path()-style lookup).
