### ISSUE TITLE
Unexpected result with std::string_view on different platform

### ISSUE THREAD

**Issue by J-Roux** [ToruNiina/toml11#182]
```cpp
TEST(toml, bug)
{
  toml::value table{};
  std::string_view data = "hello";
  table["data"] = data;
  std::cout << table << std::endl;
}
```

On Linux gcc 11.2
```
1: [ RUN      ] toml.bug
1: data = "hello"
1: 
1: [       OK ] toml.bug (0 ms)
```
On Windows  MSVC 19.29.30136.0
I expected same result and same type(string) like on Linux, but got char array. 
```
[ RUN      ] toml.bug
data = [
104,
101,
108,
108,
111,
]

[       OK ] toml.bug (0 ms)
```

**Comment by ToruNiina** [comment]
That is wired because we always test that feature and it passes on CI with various versions of MSVC.

- test code with `string_view`: https://github.com/ToruNiina/toml11/blob/master/tests/test_value.cpp#L426-L443
- CI result, especially for C++17-MSVC-Release: https://github.com/ToruNiina/toml11/runs/4547945257?check_suite_focus=true

Although I'm not 100% sure because I don't know your configuration, I think the reason why you got a weird result is that you don't set `/Zc:__cplusplus` in your MSVC configuration. It defines a macro `__cplusplus` correctly that is used to detect the version and used when checking if the environment has `<string_view>`. The macro is guaranteed to be defined by the C++ spec, but MSVC does not define it correctly unless you pass the flag, maybe because of a historical reason or for the sake of backward compatibility or something like that.

FYI: https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

**Comment by basiliscos** [comment]
Can some macros be defined, to force the behavior of inclusion of `std::string_view` ? It is quite unhandy to carry `/Zc:__cplusplus` for all dependent projects of header-only library?

**Comment by ToruNiina** [comment]
I added a workaround for MSVC's standard incompliant behavior, so now it works without `/Zc:__cplusplus`. I think this would help in most cases.

You can also use `TOML11_ENFORCE_CXX11`, `14`, `17`, `20` to use the feature of the specified standard regardless of what the compiler says.

**Comment by basiliscos** [comment]
Perfect, thank you. When to expect the release of new version of toml11?
