### ISSUE TITLE
how to format a inline table?

### ISSUE THREAD

**Issue by NaturalUser** [ToruNiina/toml11#206]
hello

i tried to make a table and it has standard format:
 [points]
x=1
y=1
z=0
[points]
x=2
y=1
......

but i just want to output a toml file with the format like below:
points = [
    { x=1, y=1, z=0 },
    { x=2, y=4, z=0 },
    { x=3, y=9, z=0 },
]
how should i do?
(sorry for poor English)

**Comment by ToruNiina** [comment]
In toml v3, there were no way to do that.
I have just released v4.0.0, allowing to specify format information.

You can now set `toml::table_format::oneline` when serializing it.

```cpp
#include <toml.hpp>
#include <iostream>
int main()
{
    toml::value v(toml::table{});
    v["points"] = toml::array{
        toml::table{ {"x", 1}, {"y", 1}, {"z", 0} },
        toml::table{ {"x", 2}, {"y", 4}, {"z", 0} },
        toml::table{ {"x", 3}, {"y", 9}, {"z", 0} },
    });
    v.at("points").as_array_fmt().fmt = toml::array_format::multiline;
    for(auto& p : v.at("points").as_array())
    {
        p.as_table_fmt().fmt = toml::table_format::oneline;
    }

    std::cout << toml::format(v) << std::endl;
    return 0;
}
```

This outputs the following.

```toml
points = [
    {z = 0, y = 1, x = 1},
    {z = 0, y = 4, x = 2},
    {z = 0, y = 9, x = 3},
]
```

The order is not preserved because `toml::value` uses `std::unordered_map` by default. If you need to preserve the order, you can use `toml::ordered_value` variants instead, like the following.

```cpp
#include <toml.hpp>
#include <iostream>
int main()
{
    toml::ordered_value v(toml::ordered_table{});
    v["points"] = toml::ordered_array{
        toml::ordered_table{ {"x", 1}, {"y", 1}, {"z", 0} },
        toml::ordered_table{ {"x", 2}, {"y", 4}, {"z", 0} },
        toml::ordered_table{ {"x", 3}, {"y", 9}, {"z", 0} },
    };
    v.at("points").as_array_fmt().fmt = toml::array_format::multiline;
    for(auto& p : v.at("points").as_array())
    {
        p.as_table_fmt().fmt = toml::table_format::oneline;
    }

    std::cout << toml::format(v) << std::endl;
    return 0;
}
```

This outputs the following.

```toml
points = [
    {x = 1, y = 1, z = 0},
    {x = 2, y = 4, z = 0},
    {x = 3, y = 9, z = 0},
]
```

Note that `toml::array` is actually `std::vector<toml::value>`, so if you use `toml::array` the `ordered_table` is converted to `std::unordered_map` and the values will be shuffled.

For more detail, please see the [doc](https://toruniina.github.io/toml11/docs/reference/format/#table_format).
