### ISSUE TITLE
Serialization issue with floating values and locale

### ISSUE THREAD

**Issue by qtnc** [ToruNiina/toml11#218]
Hello,

The serialization output is incorrect with floating type when the locale defines something else than the dot '.' as decimal separator.
'.' should always be used as decimal separator regardless of the locale.

Example compiled with MinGW-W64 8.1 under Windows 10:

    #include<toml.hpp>
    #include<iostream>
    #include<clocale>
    
    int main (int argc, char** argv) {
      const char* loc = setlocale(LC_ALL, "French_France.1252");
      std::cout << "Locale = " << loc << std::endl;
      toml::value val;
      val["test"] = 0.75;
      std::cout << val << std::endl;
      return 0;
    }

Produced output:

    Locale = French_France.1252
    test = 0,75.0

Expected output:

    Locale = French_France.1252
    test = 0.75

Naturally, that incorrect output is  rejected on input:

    toml::syntax_error: [error] toml::parse_table: invalid line format
     --> unknown file
         |
     1 | test = 0,75.0
         |           ^--- expected newline, but got ','.

Thank you !

**Comment by ToruNiina** [comment]
Yes, this is a problem.
To be honest, I actually noticed this when I learnt about locales, but left it out because I myself have never set locale and no one had pointed it out. Now that it has been pointed out, it will have to be fixed.

The standard library setlocale sets the locale of the whole process. Setting the locale to C while outputting numbers would fix the problem, but this would break the output of other threads (if any).

Luckily, Linux, Windows and Mac (BSD) each seem to provide a way to change the thread-local locale, so this can be fixed for those operating systems. That should be fine for now.

It will take some time, but I will try to fix it.
