### ISSUE TITLE
Building with C++20 and the following error is triggered

### ISSUE THREAD

**Issue by Smurf-IV** [ToruNiina/toml11#226]
I have Level 4 and warnings as errors turned on as part of the code standard we use...

This results in the following being triggered:

1>Z:\Repos\SRLE\Thirdparty\PoC\toml11\include\toml\exception.hpp(18,66): error C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

![image](https://github.com/ToruNiina/toml11/assets/2418812/7468df45-6336-4954-9c13-beffd05a66a1)

**Comment by ToruNiina** [comment]
Fixed.

Since `strerror_s` is only available in MSVC (actually it is not a part of C++), it uses `strerror_s` only when it is compiled using MSVC and uses `strerror_r` on linux.

Anyway, since the only function that may call `strerror` is the `FILE*` version of the `toml::parse`, so in most cases people would not be affected by this.
