### ISSUE TITLE
User-defined error messages and generic hints

### ISSUE THREAD

**Issue by benlad** [ToruNiina/toml11#237]
When adding a user-defined error as per the negative value check in _Formatting user-defined error messages_ from the README,

```
const auto value = toml::find<int>(data, "my_unsigned");
if(my_unsigned < 0)
{
    std::cerr << toml::format_error("[error] value should be positive",
                                    data.at("num"), "positive number required")
              << std::endl;
}
```
we still have generic hints that are misleading:

```
 --> /my_folder/my_config.toml
    |
 31 | my_unsigned = 011610
    |               ^--- here
    |
Hint: pass: -42, 1_000, 1_2_3_4_5, 0xC0FFEE, 0b0010, 0o755
Hint: fail: 1__000, 012
```

I.e. the hint still suggests negative numbers are OK when a different error occurs.  Do we have a way around this?

**Comment by ToruNiina** [comment]
The error message you pasted here is not your custom error message. Your TOML file contains a syntax error at line 31 and `toml::parse` throws the error. Since you are writing an invalid integer, `toml::parse` shows hints. `toml::format_error` is not called here.
`011610` is not a valid integer because TOML does not allow leading zeros. Maybe missing `x` in `0x` or mistakenly typed `0` instead of the next key, `-`?

Also, there are multiple problems in your code.
- You forgot to rename `value` as `my_unsigned` in the 1st line. `const auto value` should be `const auto my_unsigned`.
- You forgot to rename `num` as `my_unsigned` in the 5th line. `data.at("num")` should be `data.at("my_unsigned")`.
