### ISSUE TITLE
User-defined error messages conflict with built-in hints

### ISSUE THREAD

**Issue by benlad** [ToruNiina/toml11#238]
Sorry for posting a very similar defect to the one you closed, I don't think I was clear enough.  I don't appear to have the ability to reopen the original. Thanks for your rapid response!

TO CLARIFY:
When you create user-defined error (below) and a different error is triggered by some other problem, the hints for the triggered error may be misleading.  I have created an error to prevent negative values, but the hint for some other error says negative values are valid.  Is it possible to modify the hints for errors built in to the library, or is there some other workaround?

ORIGINAL DEFECT (with code fixes):
When adding a user-defined error as per the negative value check in _Formatting user-defined error messages_ from the README,

```
const auto my_unsigned = toml::find<int>(data, "my_unsigned");
if(my_unsigned < 0)
{
    std::cerr << toml::format_error("[error] value should be positive",
                                    data.at("my_unsigned"), "positive number required")
              << std::endl;
}
```
we still have generic hints that are misleading:

```
 --> /my_folder/my_config.toml
    |
 31 | my_unsigned = 011610
    |               ^--- here
    |
Hint: pass: -42, 1_000, 1_2_3_4_5, 0xC0FFEE, 0b0010, 0o755
Hint: fail: 1__000, 012
```
I.e. the hint still suggests negative numbers are OK when a different error occurs. Do we have a way around this?

**Comment by ToruNiina** [comment]
Okay, I got it.
But there is no such a way.

Since toml::parse does not know your application, there is no way to infer what kind of value is expected. So the only thing it can do is to check for conformance to the TOML standard.

To change hints depending on the key, a user has to pass a pair of an expected tree structure and its hints. And also the parser needs to explore the tree when it finds a new value. This requires a huge change. And constructing such a tree structure might also be too much for users.

Since it is impossible to predict the user's application, it is unrealistic to change hints to make them applicable to every kind of situation. Like, one value may require only positive integers while another may require negative integers.

So, the only option is to make it possible to disable hints globally. But I don't think it is a good idea because it reduces the information of the error message (even for non-target values), even though it requires a lot of work.
