### ISSUE TITLE
Haven't overload "=" operator for toml::table

### ISSUE THREAD

**Issue by PassingWang** [ToruNiina/toml11#244]
OS: Fedora 40
Complier: Clang++ 18.1.1
toml11: 3.7.1 from fedora official repository

```cpp
toml::table config;
...
try
{
	config = toml::parse(configPath);
}
catch(const std::exception& e)
{
	std::cerr<<"Error: "<<e.what()<<std::endl;
	return 1;
}
```

clang++ complier error:
```
main.cpp:27:10: error: no viable overloaded '='
   27 |                 config = toml::parse(configPath);
      |                 ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ToruNiina** [comment]
`toml::parse` returns `toml::value` that contains `toml::table`, not `toml::table` itself.

It is because `toml::parse` also parses additional information such as `toml::source_location` and comments (if `TOML11_PRESERVE_COMMENTS_BY_DEFAULT` is defined).

Since `toml::table` is an alias to `std::unordered_map<std::string, toml::value>`, it cannot contain comments or `toml::source_location`.
