### ISSUE TITLE
[3.7.0] toml::parse can not  handle array like testArray = [ 1.0, inf.0, ]

### ISSUE THREAD

**Issue by Isaac0106** [ToruNiina/toml11#254]
code like:

auto toml = toml::parse("testArray = [1.0, +inf]");

std::stringstream t_format;

// +inf will change to inf.0
t_format << toml;

//  terminate called after throwing an instance of 'toml::syntax_error'
//  what():  [error] toml::parse_array: missing array separator `,` after a value
   |
 1 | testArray = [
   |             ^--- array starts here
 ...
 3 | inf.0,
   |    ^--- should be `,`
toml::parse(t_format, "test")

Here, I want to merge some files and then process them together， additional processing is required here

**Comment by ToruNiina** [comment]
serializer checks `std::isfinite` and `std::isnan` (cf. https://github.com/ToruNiina/toml11/blob/master/toml/serializer.hpp#L182) and returns `"inf"` directly if the value is inf.

That means that `std::isfinite` is not working in your code maybe because of `-ffast-math` or something equivalent. That option allows compilers to optimize codes assuming that no `inf/nan` value appears while computation.

I needed `-ffast-math` to reproduce the problem. I checked out toml11-v3 and wrote the following.

```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    std::istringstream iss("testArray = [1.0, +inf]");
    std::cout << toml::parse(iss);
    return 0;
}
```

And the commands:

```console
$ g++-13 -std=c++20 issue254.cpp -O2 -Wall -Wextra -Wpedantic -Werror
$ ./a.out
testArray = [
1.0,
inf,
]
$ g++-13 -std=c++20 issue254.cpp -O2 -ffast-math -Wall -Wextra -Wpedantic -Werror
$ ./a.out
testArray = [
1.0,
inf.0,
]
```

So, remove `-ffast-math` (or equivalent option in your compiler) from compile options.
Implementing `inf/nan`-related things under that option makes code complicated and less generic.
Also, when you use `inf` value in your calculation, that option can change your results, not only toml serialization.

P.S. please update to toml11-v4. v3 will not be updated actively.
