### ISSUE TITLE
Can't figure out how to change table format

### ISSUE THREAD

**Issue by TomSteynen** [ToruNiina/toml11#273]
I'm trying to create a table, using an ordered map and with comments, and changing the indent amount.

I've defined some 'my_' types to achieve the ordered map and comments:

```
struct my_config
{
    using comment_type = preserve_comments;
    using boolean_type = bool;
    using integer_type = std::int64_t;
    using floating_type = double;
    using string_type = std::string;
    template<typename T>
    using array_type = std::vector<T>;
    template<typename K, typename T>
    using table_type = tsl::ordered_map<K, T>;
    static result<integer_type, error_info> parse_int(const std::string& str, const source_location src, const std::uint8_t base)
    {
        return read_int<integer_type>(str, src, base);
    }
    static result<floating_type, error_info> parse_float(const std::string& str, const source_location src, const bool is_hex)
    {
        return read_float<floating_type>(str, src, is_hex);
    }
};

using my_basic_value = basic_value<my_config>;
using my_value = my_basic_value::value_type;
using my_table = my_basic_value::table_type;
```

This works. So now I want to change the table_format_info::body_indent. But I can only call as_table_fmt on a my_basic_value, I can't call it on a my_table. So when I try the code below, it doesn't compile:

```
toml::my_table t;
toml::table_format_info& format= t.as_table_fmt();  <== compile error: t has no member as_table_fmt
format.body_indent = 4;
```

I tried constructing t as a my_basic_value but then it throws an exception on as_table_fmt because it's type isn't initialized.

```
toml::my_basic_value t;
toml::table_format_info& format = t.as_table_fmt(); <== throws
format.body_indent = 4;
```

How should I handle this? Why can't I change the table format directly on a toml::table type?

Thanks,
Tom

**Comment by ToruNiina** [comment]
`basic_value::table_type` is a map-like container type itself, as `basic_value::integer_type` is `std::int64_t` itself. By default (`toml::value::table_type`), it is `std::unordered_map<std::string, toml::value>` and in your case, `tsl::ordered_map<std::string, toml::value>`. You can do anything you can do with the container type, but it does not have any toml-related stuff because they are just containers.

So, here:

```cpp
toml::table_format_info& format= t.as_table_fmt();  <== compile error: t has no member as_table_fmt
```

type of `t` is `tsl::ordered_map<std::stirng, my_basic_value>`. It of course does not have `as_table_fmt()` because `tsl::ordered_map` is not related to TOML.

This is the reason of the compile error.

----

`toml::basic_value` becomes empty if it is initialized without any value.

```cpp
toml::value v1;        // empty
toml::value v2(42);    // integer
toml::value v3("foo"); // string
toml::value v4(toml::table{ // table
        {"foo", 42},
        {"bar", "baz"}
    });
```

A `toml::value` having an integer value does not have any format info about table. Similar to that, an empty `toml::value` does not have any format information. When you call `as_table_fmt` for an empty `toml::value`, it throws because an empty value does not have `table_format_info`.

If you know about `std::variant`, you can think `toml::value` is something similar to the following:

```cpp
struct basic_value
{
    std::variant<
        std::monostate,
        std::pair<std::int64_t, integer_format_info>,
        // ...
        std::pair<table_type, table_format_info>
    > internal_;
};
```

Of course the actual implementation is completely different, but is similar to this in some sense.

To activate `table_format_info`, you need to initialize the `value` with a `table`.

```cpp
toml::my_basic_value t(toml::my_table{});
toml::table_format_info& format = t.as_table_fmt();
format.body_indent = 4;
```

This is the way to handle `something_format_info`.

----

`tsl::ordered_map` defines `iterator` type in a slightly different way from the standard library `std::map`. Because of that, it does not compile with some features of toml11 because toml11 requires `table_type` to have the same interface as the `std::unordered_map`. You may encounter a problem later.

You can also use `toml::ordered_map`. It defines `toml::ordered_value` that uses `toml::ordered_map` as the `table_type`. Although key lookup of `toml::ordered_map` is not fast with large map, but at least it works.

----

Although it is just a matter of preference, you don't need to define `my_config` in `namespace toml`. You can define it in your namespace, and you can use it with toml11.

```cpp
namespace ext
{
struct some_config { /*...*/ };
} // ext

toml::basic_value<ext::some_config> v1(42);
```

or

```cpp
namespace ext
{
struct some_config { /*...*/ };
using toml_value = toml::basic_value<ext::some_config>;
using toml_table = toml_value::table_type;
using toml_array = toml_value::array_type;
} // ext

ext::toml_value v1(42);
ext::toml_value v2(ext::toml_table{
        {"foo", 42}, {"bar", "baz"}
    });
```

**Comment by TomSteynen** [comment]
Hi thanks, I got it to work.

It seems that I got things muddled by thinking my_table was some kind of wrapper around a toml::basic_value initialized as a table. Which it obviously isn't if I look again at the my_config definition.

I remember trying to initialize a value as a table once, but I think I tried it like this:
`toml::my_value t(toml::my_table());`
instead of this:
`toml::my_value t(toml::my_table{});`
which didn't work and just added to my confusion.

Thanks for the extensive explanation.

PS: I realize I didn't need to define the my_ things in the toml namespace. It was indeed a preference choice.
