### ISSUE TITLE
parsing error creates a string that is too long when in column 0

### ISSUE THREAD

**Issue by hayt** [ToruNiina/toml11#275]
https://github.com/ToruNiina/toml11/blob/4b740127230472779c4a4d71e1a75aaa3a367a2d/include/toml11/impl/source_location_impl.hpp#L119 is not checking if `col` is 0 and creates a UINT_MAX length string when you have an error in column 0. In VS this causes the string to throw a `std::length_error`.

I encountered this error, when I passed an empty string into `try_parse_str` with Visual studio 2022 and c++20 enabled. (`toml::try_parse_str("");`)

**Comment by ToruNiina** [comment]
Nice catch! Do you want to make a pull request to fix this error?
If you want to make a pull req, please reply (or just send a pull req) before the next monday. If not, I will fix it on the next monday.

**Comment by hayt** [comment]
I can look into that. What would be the ideal behavior here? 
I just checked the origin of the exception, I haven't looked into what exactly the function does, so I don't know what would be best. Just pass in something like `col == 0 ? 0 : col-1`?

**Comment by ToruNiina** [comment]
`col == 0 ? 0 : col-1` is okay.

The function generates underline that points where the error happens. And the line you pointed adds padding in order to make underline starts at the exact location where the parser fails.
In this case, we don't have any TOML content, so there will be no padding at all.
