### ISSUE TITLE
Does this implementation preserve comments when writing a table read from a file?

### ISSUE THREAD

**Issue by thejohnfreeman** [ToruNiina/toml11#48]
Question in the title. I'm looking for a comment-preserving parser and printer.

**Comment by ToruNiina** [comment]
Sorry, it doesn't. All comments will be wiped out after parsing toml file.

**Comment by ToruNiina** [comment]
Hi,

Sorry for the confusing reply. Actually, I found (and you may have already found?) that there is a way to extract comments that are described around a `toml::value`.

Although the parser skips comments in a file, as mentioned in the README, the contents of a file remains on memory unless all the `toml::value`s are destructed. So essentially I can implement a function to find comments that are written before and after the value. I pushed a proof-of-concept function to a branch named `experimental-preserve-comment`.

However, because it searches file contents, it doesn't work with values that are constructed in a C++ code. It means that there is no way to modify the comments. In order to modify the comments, we need to add one `std::string` or something like that to `toml::value`, but I don't know if it is the right place.

In the future release, hopefully 2.3, the functionality to read comments related to a value would be introduced. But enabling to modify a comment is a bit different stuff, so I'd like to think about it more carefully.

**Comment by thejohnfreeman** [comment]
Oh, that's actually a good start. The motivating use case for me is human- and machine-editable configuration: my program should be able to read a configuration written by a human, possibly with comments, and change values without disturbing comments on (i.e. immediately before) those values; add values without putting them in-between an existing value and its comment; or remove values without removing comments.

**Comment by ToruNiina** [comment]
It took a long time, but I've added a `toml::value::comment` function to get comments related to a value.

But currently, once a value is modified, information about which part in a file corresponds to the value will be removed because the region is no longer corresponds to a value. It means that after modifying data, comments are not able to be obtained. Thus currently it is impossible to modify a data keeping a comment. To put a comment, comments need to be written manually while serialization.

As I said before, adding a member variable that represents comments to a value is a large change. So the change would possibly be made in version 3.

**Comment by ToruNiina** [comment]
Hi, sorry for the late reply but this feature has been supported after v3.

You can specify `preserve_comments` via `toml::parse` function and then you can read/write a comment on a value.

```cpp
auto data = toml::parse<toml::preserve_comments>("example.toml");
data.at("v1").comments().push_back(" this is a comment");
std::cout << data;
```

```toml
# this is a comment
v1 = "foo"
```

For more detail, please see [here](https://github.com/ToruNiina/toml11#preserving-comments).
