### ISSUE TITLE
Parsing a vector of floats

### ISSUE THREAD

**Issue by xaxousis** [ToruNiina/toml11#50]
I'm not sure whether this is an issue or whether it is intended : I'm not too confident about how the spec says this should be handled.

When parsing into a `std::vector<float>`, an array value with integers raises an error.

```
# This wont work
test_array = [1, 2, 3]

# This will work
test_array = [1.0, 2.0, 3.0]
```

If you don't manage to reproduce, I will try to come up with a code example.

**Comment by ToruNiina** [comment]
The behavior is intended, at least on the current stage.

It is because `toml::get<array_like_type>` calls `toml::get<element_type>` internally and currently `tom::get` does not convert `Integer` to `Float`.

The reason why `toml::get` does not convert `Integer` to `Float` is that `toml::get<double>` can return an lvalue-reference through which we can modify the content of `toml::value`. To do that, since we cannot return a reference of a value in a function scope, I need to prohibit conversions. As the conversion from `Integer` to `double` is not supported, I also disabled conversions between `Integer` and `float`, for the consistency.

I know the behavior is useful (actually, sometimes I myself also want this functionality). I'm considering implementing a function `toml::as` that converts `Integer` to `Float` and any other possible conversions. But I'm also worrying that having both `toml::get` and `toml::as` might be confusing.

**Comment by xaxousis** [comment]
I see your point. I'm not sure I have any idea of how to improve this so I'll close the issue for now.

I think I'll create a custom type that can set a float from an integer for the time being.
