### ISSUE TITLE
add option to load default values

### ISSUE THREAD

**Issue by Thomas131** [ToruNiina/toml11#6]
Hello!
It would be awesome to have the option to load default Values. That if a key isn't found in the toml-file, the default value is taken.

Best Regards!
Thomas

**Comment by ToruNiina** [comment]
Hello, Thomas.

It sounds nice.
I added `toml::get_or()` function to be able to load default values.

```cpp
toml::Table data; // empty table!

const auto value1 = toml::get_or(data, "key1", 42); // value1 => int 42.

toml::Integer i(123);
const auto value2 = toml::get_or(data, "key1", i);  // value2 => toml::Integer 123.
```

Since `toml::Table` is just an alias of `unordered_map<key, value>`, it is not possible to add member function like `table.at_or("key", optval)`.

`toml::get_or` internally call `toml::get<T>` if the table has the value corresponding to the key.
The type `T` for `toml::get` is deduced from the type of the optional value.

Best,
Niina
