### ISSUE TITLE
Pass line number and filename for exception

### ISSUE THREAD

**Issue by khoitd1997** [ToruNiina/toml11#62]
Hi, while the default error message for things like ```toml::syntax_error``` is quite nice, I would prefer to output my own format and the ```format_error``` doesn't quite cut it, is it possible to pass data like line number, file name and the error message in an exception?

**Comment by ToruNiina** [comment]
Do you mean that you want to get a line number, file name, and an error message itself that corresponds to an exception? If so, there is no way to extract them from an exception that is already thrown because it only has a string.

In the next (major) release, I may consider providing a struct that has information something like `std::experimental::source_location`.

From `toml::value`, you can extract information about where the value defined in a file. But to do that, you need to call the functions that are under the namespace `toml::detail` (you can see the usage in `toml/get.hpp line 238, for example`). Note that those functions are considered to only be used internally and may be changed without any announcement.

**Comment by khoitd1997** [comment]
Do you know when the next major release is coming? And anything I can help to make the feature happens?

**Comment by ToruNiina** [comment]
> when the next major release

No, because it is my personal project, I don't have any strict schedule or deadline.

> And anything I can help to make the feature happens?

Changing non-static member variable defined in an exception requires a large change of the implementation of the parser. The current implementation assumes that error messages are passed as a string. This "large change" does not only mean that it requires a lot of tasks, but it requires design decisions before making changes. I'm still thinking about the best way to do that  (actually, I'm trying some possible designs).

For a walkaround, especially extracting that information from an exception that is already thrown from `toml::parse`, you can parse the message. The first line of the error message is always a brief error message. The second line starts `--> ` and the input file name follows that. And the rest of the message includes the error region with line number. A line number is always before a bar `|`, so you can always skip a portion of a line after `|`, to get a line number.
