### ISSUE TITLE
unknown table when using find without data.at(table)

### ISSUE THREAD

**Issue by zrsmithson** [ToruNiina/toml11#64]
Using the find function gives good log messages when there's a chance the config file might get broken from someone editing it. But it has unexpected behavior when using an already built toml::table value instead of data.at("table").

For example, when a key is not found in a subtable:
```
[table]
vallue = "num"
```
I would expect the following exmaples to be the same, but it is not the case as you can see from the output.
```
toml::table data = toml::parse(config_filename);
const auto table = toml::get<toml::table>(data.at("table"));
std::string value = toml::find<std::string>(table, "value");
```
> ```
> [error] key "value" not found in unknown table
> ```

but by getting the (non-casted to toml::table, if I understand correctly) value from the table, it prints out a better error message

```
toml::table data = toml::parse(config_filename);
std::string value = toml::find<std::string>(data.at("table"), "value");
```
> ```
> [error] key "value" not found
>  --> ~/config.toml
>  74 | [table]
>     | ~~~~~~~ in this table
> ```

**Comment by ToruNiina** [comment]
Sorry for the confusing behavior, but it is intended.

toml11 uses `std::unordered_map<toml::key, toml::value>` internally and, as mentioned in README, `toml::table` is just an alias of it. Since `std::unordered_map` does not have any information about toml, `toml::find` cannot get where the table is.

There are mainly 2 reasons why I chose the current design. First, `std::unordered_map` is a well known STL container so users do not need to check a document of toml11 to know what member functions are available (one may need to check a reference of C++ but there are a number of nice resources). Second, I don't need to pay a cost for re-implementing all the interfaces that are essentially the same as `std::unordered_map`.

Thus, after you get `toml::table`, you can use all the functionalities available with `std::unordered_map` (e.g. `find`, `count`, `operator[]`) but not toml-related features. If you want to use both interfaces, the current solution is to keep `toml::value` and try `toml::value::as_table()`. `v.as_table()` is effectively the same as `toml::get<toml::table>(v)`, but it is shorter and easy to read, I think.

**Comment by zrsmithson** [comment]
So to clarify, the best way to do what I'm hoping is to get the table as a `toml::value` and explicitly call `as_table()` if I ever wanted to use `unordered_map` function. So changing my generic example above, I just need to get the table as a `toml::value` instead.

```
toml::table data = toml::parse(config_filename);
const auto table = toml::get<toml::value>(data.at("table"));
std::string value = toml::find<std::string>(table.as_table(), "value");
```

> ```
> [error] key "value" not found
>  --> ~/config.toml
>  74 | [table]
>     | ~~~~~~~ in this table
> ```

**Comment by ToruNiina** [comment]
It's my pleasure!

And there is just one more thing. The template parameter of `toml::find<T>` has a default value `toml::value`. So *if you want*, you can omit the parameter and the code looks like the following.

```cpp
toml::table data = toml::parse(config_filename);
const auto& table = toml::find(data, "table");
std::string value = toml::find<std::string>(table, "value");
```
