### ISSUE TITLE
Questions regarding warnings

### ISSUE THREAD

**Issue by khoitd1997** [ToruNiina/toml11#66]
Hi, I noticed that ```toml11``` warnings mostly come from type conversion warnings such as using ```size_t``` in places that use ```int```. Are they deliberate choices? The ones that I have looked at don't seem to look that serious so I want to put PRs in to make the warning list cleaner and thus making it easier to use with projects that have stringent compilation requirements like ```-Werror``` without adding additional options for ```toml11``` in ```CMake``` such as making it be considered as a system header. Thank you for your work, ```toml11``` is a joy to use.

**Comment by ToruNiina** [comment]
Thank you for the suggestion.

I usually use `size_t` when the value represents a size of type, length of a container, index of a container and something that is similar to them. But if an existing STL function returns int, I would use `int` for the consistency.

I would like to clarify the environment in which you found the warnings. On Linux, with gcc, I couldn't find any warnings (e.g. you can see the result with g++-8 [here](https://travis-ci.org/ToruNiina/toml11/jobs/543106362) ). Actually, I use `-Wall -Wextra -Werror` when compiling a test code on [CircleCI](https://circleci.com/gh/ToruNiina/toml11/173) using g++. So, if g++ warns my code, at least CircleCI fails.

And now I found that clang++-7 and 8 show some warnings about the usage of rvalue references while clang++-6, 5, 4, 3.7 not. But it seems not to be the same as the warnings you reported (you can see it [here](https://travis-ci.org/ToruNiina/toml11/jobs/543106368)). Anyway, I will fix this warnings soon.

On windows, I know that MSVC shows too many warnings on Appvayor. But it seems that MSVC warns not only my toml11 but also Boost.Test library a lot (I think it is a kind of false-positive). This makes difficult to find which portion of my code causes the warnings. Since I don't have any Windows machine, to me, it is relatively difficult to check and remove the warnings. If you have any idea about warnings on Windows and MSVC, it is really helpful to me.

So, I would like to ask which environment you are using.

**Comment by khoitd1997** [comment]
Hi, thank you for the fast response, my gcc version is ```9.1.1``` on ```fedora 31```. I just recompiled and one of the errors reported was in ```toml11/toml/combinator.hpp:48:18``` with the message:
```comparison of integer expressions of different signedness: ‘const int’ and ‘std::array<char, 5>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]``` which seems like an accurate warning  as ```snprintf``` will return int while ```std::array size()``` will return ```size_t```

**Comment by ToruNiina** [comment]
Thank you for the detailed report.
Sorry, I didn't try gcc-9.1 so I overlooked it. It IS a bug. If you are creating a PR, I will merge it soon.

**Comment by ToruNiina** [comment]
Thank you for the PR.
If you have already found some other potential defect, PRs are welcome.
