### ISSUE TITLE
Preserving order for tables

### ISSUE THREAD

**Issue by NikolausDemmel** [ToruNiina/toml11#71]
Is there a way to control the order of how elements in a table are serialized? From the readme it seems the tables are implemented as unorderd_map, so I guess that currently results in a (more or less) random order.

For example, it would be nice to optionally have the output preserve the order of the how keys are entered into the table.

For example in https://github.com/nlohmann/json this is realized by providing a template argument that specifies the type used internally to store the table, where one can specify a map data structure that preserves order, see https://github.com/nlohmann/json/issues/546#issuecomment-304447518 and https://github.com/nlohmann/json/issues/485#issuecomment-333652309

**Comment by ToruNiina** [comment]
Thank you for the suggestion and information.

You are right, the current implementation does not preserve the order of the keys while serialization.

In the last few months, I was working on the next major update. Although I didn't think about the key-order problem, the next major release will include [custom container support](https://github.com/ToruNiina/toml11/tree/v3#customizing-containers) in the similar (a bit different, but essentially the same) way as you mentioned. 

The main reason why I changed the definition of `toml::value` was to support comments in a more powerful way. While I was introducing a template argument to it, I added custom container support for providing a way to optimize the performance and memory usage in some cases. It is nice to hear that it might be helpful also for other purposes.

Now it is still a beta release and has not been merged into master yet, but you can [try it](https://github.com/ToruNiina/toml11/releases/tag/v3.0.0-beta). It already passes the same tests that are applied to the current version, but I plan to merge it after I try it with some of my own tools because it includes breaking changes.

**Comment by ToruNiina** [comment]
Sorry for the late reply. After v3, you can specify STL-like containers that would be used in `toml::value`.

```cpp
const auto data = toml::parse<
    toml::preserve_comments, std::map, std::deque
    >("example.toml");
```

For more detail, please see [here](https://github.com/ToruNiina/toml11#customizing-containers).

**Comment by NikolausDemmel** [comment]
Thanks for the updates! I just check out version 3. It works great with `fifo_map` as well, as in:

```
using ordered_toml = toml::basic_value<toml::discard_comments, nlohmann::fifo_map, std::vector>;
```

With that, it preserves the insertion order, which is nice if you want to write back or output in the initial order from the config file.

https://github.com/nlohmann/fifo_map
