### ISSUE TITLE
include toml.hpp in example is incorrect?

### ISSUE THREAD

**Issue by russkel** [ToruNiina/toml11#72]
Hi,

The example in the README currently shows:

```
#include <toml11/toml.hpp>
#include <iostream>
```
But that file doesn't exist with my CMake installed library. I have to use `#include <toml.hpp>`. Maybe the example[s] needs an update?

**Comment by ToruNiina** [comment]
Yes, you are right.

I thought it is helpful to explicitly write a repository name because cmake did not support `install` command when I wrote it. At that time, I supposed that this library would be installed as a git submodule or be cloned under the project directory.

But now I think it is nicer to have `#include <toml.hpp>` there since there are several way to install it and also the directory name could be changed.

**Comment by russkel** [comment]
Fair enough. Feel free to close this if it was personal choice. I thought it was an artefact of a previous toml11 era.

**Comment by ToruNiina** [comment]
updated.
