### ISSUE TITLE
question and suggestion

### ISSUE THREAD

**Issue by peterritter** [ToruNiina/toml11#81]
After having used toml11 for a few days, I can say that its feature set is comprehensive and a lot of works has gone into making it. Thank you for that!! It will be very useful to me!

However, in terms of usability, I find access to values a bit tedious, with multiple methods of accessing data, some of which are quite tedious.
 
I have the following suggestion: Add operator[] to toml::value so that we can easily chain invocations using either string or numeric arguments like so:

		toml::value root;
		auto v = root["fruit"]["apple"]["colors"][1].as_string();

This could then also be used for setting values: 

                root["fruit"]["apple"]["colors"][1] = "green";

For my own usage, I tried to add these operators, but the compiler is giving me an error which I'm not sure how to fix. Maybe it's an easy fix? 
I think that this would not break any existing code and would provide a unified alternate method to access data in both arrays and tables!

I added this to class basic_value in value.hpp.

	basic_value operator[](size_t pos)
    {
		if (!is_array())
			throw std::exception("not an array, cannot access position: " + std::to_string(pos));
		return as_array().at(pos);
    }

	basic_value operator[](const std::string& key)
	{
		if (!is_table())
			throw std::exception("not a table, cannot access key: " + key);
		return as_table().at(pos);
	}

	basic_value operator[](const char* key)
	{
		if (!is_table())
			throw std::exception("not a table, cannot access key: " + std::string(key));
		return as_table().at(pos);
	}

the compiler error is:
1>c:\users\ritte\_pr_dev_\dev_projects_git\tsapi_unit_tests\source\test_23000_toml.cpp(399): error C2678: binary '[': no operator found which takes a left-hand operand of type 'const toml::value' (or there is no acceptable conversion)
1>c:\users\ritte\_pr_dev_\dev_projects_git\tsapi_source\source\tsa\toml11\toml\value.hpp(1335): note: could be 'toml::basic_value<toml::discard_comments,std::unordered_map,std::vector> toml::basic_value<toml::discard_comments,std::unordered_map,std::vector>::operator [](const char *)'
1>c:\users\ritte\_pr_dev_\dev_projects_git\tsapi_source\source\tsa\toml11\toml\value.hpp(1328): note: or       'toml::basic_value<toml::discard_comments,std::unordered_map,std::vector> toml::basic_value<toml::discard_comments,std::unordered_map,std::vector>::operator [](const std::string &)'
1>c:\users\ritte\_pr_dev_\dev_projects_git\tsapi_source\source\tsa\toml11\toml\value.hpp(1321): note: or       'toml::basic_value<toml::discard_comments,std::unordered_map,std::vector> toml::basic_value<toml::discard_comments,std::unordered_map,std::vector>::operator [](size_t)'
1>c:\users\ritte\_pr_dev_\dev_projects_git\tsapi_unit_tests\source\test_23000_toml.cpp(399): note: while trying to match the argument list '(const toml::value, const char [6])'

Thank you for considering this!

**Comment by ToruNiina** [comment]
Thank you for the suggestion!

It seems that your methods lack `const` specifier. As the compiler says, non-const methods cannot be called if the object or reference is marked const.

So adding `const` to the member function or removing `const` from `toml::value` will fix the code (I didn't check it yet).

```cpp
basic_value operator[](size_t pos) const // this
{
	if (!is_array())
		throw std::exception("not an array, cannot access position: " + std::to_string(pos));
	return as_array().at(pos);
}
```

And yes, as you pointed out, those methods would be useful in some cases. I also considered to add them previously, but I didn't add it at that time because I personally didn't need them. My application code reads configs table by table, so in my case, each `toml::find` call corresponds to each `read_xxx_config` function that returns an object. Additionally, although it does not affect the overall runtime efficiency, I didn't want to check the existence of a value twice. That's the reason why I didn't add it. But it is just one case. If it is needed, I will re-consider to add them. If you have a PR, it's always welcome.

The difficulty is that the consistency between `toml::value` and STL containers. `std::vector::operator[]` effectively does not throw (when the index is out-of-bounds, it just causes undefined behavior) and `std::map::operator[]` hardly throws unless key-value pair construction throws or memory allocation failed. But `toml::basic_value::operator[]` often throws because there is no other way to handle invalid type.

Also, `std::map::operator[]` construct a new value if the key is not found. But `std::vector::operator[]` doesn't. Although I prefer these behaviors, considering these, I think there is no intuitive behavior for `toml::value::operator[]` because it can store either a table or an array.

So I think it is good to have `toml::value::at()` rather than `toml::value::operator[]`. `at()` always checks the bounds and throws if the specified index or key is not found. With `at()`, we can throw an exception if the conversion or element access failed.

**Comment by ToruNiina** [comment]
Recently I got independent but identical suggestion about `operator[]`. It convinces me that this feature is strongly desired. So I have implemented it.

Note that I've implemented it in STL-like manner. `v.at(1)` checks if `v` is an array and its length is larger than 1. Contrary, `v[1]` does not check anything and never throws. If you need type- and bound-checking, use `v.at(n)`.
