### ISSUE TITLE
Using parse() fails on strings.

### ISSUE THREAD

**Issue by cmaughan** [ToruNiina/toml11#88]
Consider:
```
std::string valid_toml("foo = 32\nbar = 3");
std::istringstream is(valid_toml, std::ios_base::binary | std::ios_base::in);
auto table = toml::parse(is, path.string());
```
This is when you need to pass not a file, but a string to be parsed.  The parse step creates an invalid line error.  I suspect it is because it doesn't check for the end of the string correctly, but I'm not sure.  I tried various combinations of line endings, but maybe there is a simpler way to parse a string?

**Comment by cmaughan** [comment]
When I tried your simple test it worked for me too; but inside my app I got:

[error] toml::parse_table: invalid line format
....
1 | foo = 32

If I passed the same string to cpptoml it worked as well (I was previously using cpptoml but moved to toml11)

After debugging I narrowed it down.
What appears to be happening is that my std::string is 0 terminated (probably because it was loaded previously from a file).  But the checks in toml11 do `loc.iter() != loc.end().`  The problem is that for a null terminated string, the end iterator points to the location _after_ the terminator, so this check is no good for determining the 'end'.

If you modify your test and do this:
std::string valid_toml("foo = 32\nbar = 3");
valid_toml.push_back(0);

You will get the exception.
You might argue that the correct fix is not to pass 0 terminated strings.  I'm not sure.

BTW, I'm on Windows, VC2019.

**Comment by ToruNiina** [comment]
Thank you, I reproduced it. It makes sense.

Actually there is already an error message to show the character that causes a problem (https://github.com/ToruNiina/toml11/blob/master/toml/parser.hpp#L1809), but the error message after the line that causes the error is terminated because of `\0` at the end of the line.

Anyway, I can fix this. After loading `istream` content, I can check whether the last character and remove it if it is the null character. Although it is not helpful if a string has a null character at the middle, but I can assume such a case is exceptional.
