### ISSUE TITLE
python binding?

### ISSUE THREAD

**Issue by bobfang1992** [ToruNiina/toml11#91]
This is a feature suggestion: as all current python implementation of `toml` are in pure python and potentially slow, shall we try use `pybind11` and have a python binding for this, to give user more choice when it comes to python toml libraries?

**Comment by ToruNiina** [comment]
Sorry for the late reply. And thank you for the suggestion.

I'm sorry but, currently, I don't have any plan to provide a python interface because designing, implementing and maintaining it is a relatively heavy task.

Having said that, since toml11 is distributed under a permissive license (MIT), no one is restricted from implementing python binding as another repository.
