### ISSUE TITLE
Issue with intel compiler

### ISSUE THREAD

**Issue by bandokihiro** [ToruNiina/toml11#97]
I am using this great library for a computational fluid dynamics code. I use it to process my input files. It works without any issue with GNU compilers. When running simulations on intel-based clusters, it is often recommended by the provider to use intel compilers to get the most out of optimization.

I noticed some issues with the intel compiler `icpc (ICC) 18.0.3 20180410`. I managed to make it work by modifying some stuff in `toml/comments.hpp` but I have not tried to understand what I was really doing so I don't know if my modifications will have side-effects. Maybe you can solve this compatibility issue in a better way.

Basically I get these types of errors:
```
/nobackupp2/kbando/Libraries/toml11/toml/comments.hpp(86): error: no instance of overloaded function "std::vector<_Tp, _Alloc>::insert [with _Tp=std::string, _Alloc=std::allocator<std::string>]" matches the argument list
            argument types are: (toml::preserve_comments::const_iterator, const std::string)
            object type is: toml::preserve_comments::container_type
          return comments.insert(p, x);
```
```
/nobackupp2/kbando/Libraries/toml11/toml/comments.hpp(112): error: no instance of overloaded function "std::vector<_Tp, _Alloc>::erase [with _Tp=std::string, _Alloc=std::allocator<std::string>]" matches the argument list
            argument types are: (toml::preserve_comments::const_iterator)
            object type is: toml::preserve_comments::container_type
      iterator erase(const_iterator pos) {return comments.erase(pos);}
```
I solved those by using ```using const_iterator = container_type::iterator``` and make all those ```insert```, ```emplace``` and ```erase``` methods return nothing (```void```). 

Then because of the first modification, I had to explicitely specify
```
container_type::const_iterator begin()  const noexcept {return comments.begin();}
container_type::const_iterator end()    const noexcept {return comments.end();}
container_type::const_iterator cbegin() const noexcept {return comments.cbegin();}
container_type::const_iterator cend()   const noexcept {return comments.cend();}
```
Please find attached the ```stderr``` output I got when compiling from the official version.

Thanks!

[log.txt](https://github.com/ToruNiina/toml11/files/4178564/log.txt)

**Comment by ToruNiina** [comment]
Thank you for reporting the issue and the detailed report!

Although my environment is a bit different from yours, I succeed to reproduce the problem.

In my opinion, it is a bug in standard library implementation included in GCC 4.8.x. According to the standard draft [N3337](https://github.com/cplusplus/draft/blob/master/papers/n3337.pdf) (almost equivalent to C++11) § 23.3.6.1,  the declaration of `std::vector::insert` must be `std::vector::insert(const_iterator position, ...).` But the log.txt shows that it is implemented as `insert(iterator position, ...)`. Because of the const-correctness, we cannot convert a `const_iterator` to an `iterator`. So gcc-4.8.x's standard library implementation is not compatible with C++11. The same applies to `erase`. After some googling, I found several discussions related to this topic, e.g. https://stackoverflow.com/a/47570065.

It seems that the intel compiler uses gcc-4.8 headers in your environment. If you have installed the more recent gcc, it is helpful to use `-gxx-name` option to specify a path to the g++ executable like the following.

```console
$ icpc -std=c++11 main.cpp -gxx-name=/path/to/bin/g++ -gcc-name=/path/to/bin/gcc
```

Another option is to set the environment variable, `GXX_ROOT`.
cf. https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-supported-environment-variables

But I know it is painful to use this kind of workaround. I will look into some macros to detect the gcc version and try to resolve this issue later.

**Comment by bandokihiro** [comment]
It worked, thank you very much for this prompt solution.

**Comment by ToruNiina** [comment]
Hi, I added a macro to change the `iterator` types depending on the compiler version. Now it works fine on GCC 4.8.5 also. I hope it also works with the intel compiler that uses GCC 4.8.5 STL implementation.

**Comment by bandokihiro** [comment]
Thank you. I ended up delaying the use of intel compiler because I use something that is better tested with GNU. I will eventually try it and keep you posted. I appreciate the help.
